/* Generated by tools/generate_original_credits.py; do not edit.
 * Original Xbox (2001) roster: docs/original-xbox-credits.json.
 * Role order and source differences are recorded with the roster.
 */
#ifndef HALO_ORIGINAL_CREDITS_H
#define HALO_ORIGINAL_CREDITS_H

#define HALO_OG_ORIGINAL_CREDITS_TITLE "Original Halo: Combat Evolved - Xbox (2001)"
#define HALO_OG_ORIGINAL_CREDITS_SOURCE_URL "https://halo.bungie.org/misc/cutscenes/halo.html?cs=32"
#define HALO_OG_ORIGINAL_CREDIT_SECTION_COUNT 45
#define HALO_OG_ORIGINAL_CREDIT_PAGE_COUNT 29

struct halo_original_credit_section {
    const char *role;
    const char *const *names;
    unsigned count;
};
struct halo_original_credit_page {
    const char *text;
};

static const char *const halo_original_credit_names_0[] = {
    "Jason Jones",
};

static const char *const halo_original_credit_names_1[] = {
    "Hamilton Chu",
};

static const char *const halo_original_credit_names_2[] = {
    "Rick Ryan",
};

static const char *const halo_original_credit_names_3[] = {
    "Chris Butcher",
    "Bernie Freidin",
    "Charlie Gough",
    "Mat Noguchi",
    "Matt Segur",
};

static const char *const halo_original_credit_names_4[] = {
    "Eamon McKenzie",
    "Ben Wallace",
};

static const char *const halo_original_credit_names_5[] = {
    "Marcus Lehto",
};

static const char *const halo_original_credit_names_6[] = {
    "Steve Abeyta",
};

static const char *const halo_original_credit_names_7[] = {
    "Eric Arroyo",
    "Chris Barrett",
    "Mark Bernal",
    "David Dunn",
    "Chris Hughes",
    "Chris Lee",
    "Robert McLees",
    "Stephen Okasaki",
    "Paul Russel",
    "Shi Kai Wang",
    "Michael Wu",
};

static const char *const halo_original_credit_names_8[] = {
    "Brian Schultz",
};

static const char *const halo_original_credit_names_9[] = {
    "John Howard",
};

static const char *const halo_original_credit_names_10[] = {
    "Paul Bertone",
    "Tyson Green",
    "Jaime Griesemer",
    "Dan Orzulak",
};

static const char *const halo_original_credit_names_11[] = {
    "Brannon Boren",
    "Matt Soell",
    "Eric Trautmann",
};

static const char *const halo_original_credit_names_12[] = {
    "Michael Evans",
};

static const char *const halo_original_credit_names_13[] = {
    "Adrian Perez",
    "Stefan Sinclair",
};

static const char *const halo_original_credit_names_14[] = {
    "Hardy LeBel",
};

static const char *const halo_original_credit_names_15[] = {
    "Chris Carney",
    "Peter Marks",
    "Derrick Moore",
    "Stephen Okasaki",
};

static const char *const halo_original_credit_names_16[] = {
    "Joseph Staten",
};

static const char *const halo_original_credit_names_17[] = {
    "Steve Abeyta",
    "Paul Clift",
    "Adam Crockett",
    "Lorraine McLees",
    "Stephen Okasaki",
};

static const char *const halo_original_credit_names_18[] = {
    "Lee Wilson",
};

static const char *const halo_original_credit_names_19[] = {
    "Craig Mullins",
};

static const char *const halo_original_credit_names_20[] = {
    "Martin O'Donnell",
};

static const char *const halo_original_credit_names_21[] = {
    "Jay Weinland",
};

static const char *const halo_original_credit_names_22[] = {
    "Michael Salvatori",
};

static const char *const halo_original_credit_names_23[] = {
    "Adam Tewes",
};

static const char *const halo_original_credit_names_24[] = {
    "Max Hoberman",
};

static const char *const halo_original_credit_names_25[] = {
    "David Candland",
};

static const char *const halo_original_credit_names_26[] = {
    "Stefan Sinclair",
};

static const char *const halo_original_credit_names_27[] = {
    "Harold Ryan",
};

static const char *const halo_original_credit_names_28[] = {
    "Curtis Creamer",
    "Ryan Hylland",
};

static const char *const halo_original_credit_names_29[] = {
    "Keith Steury",
};

static const char *const halo_original_credit_names_30[] = {
    "Chris Chamberlain",
    "Mike Cody",
    "Chuck Cooper",
    "Erik Davis",
    "John Frey",
    "Rick Lockyear",
    "Paul Pedersen",
    "Zach Russell",
    "Matthew Shimabuku",
    "Luke Timmins",
    "Jeff Wilson",
    "Roger Wolfson",
    "Jeff Kafer",
    "Todd Schultz",
};

static const char *const halo_original_credit_names_31[] = {
    "Jen Taylor",
    "Pete Stacker",
    "Tim Dadabo",
    "Steve Downes",
    "Tawnya Pettiford-Waites",
    "David Scully",
    "Mike Madeoy",
    "Mark Dias",
    "Chris Wicklund",
    "Andrew McKaige",
};

static const char *const halo_original_credit_names_32[] = {
    "Ken Boynton",
    "Todd Licea",
    "Jeff Steitzer",
    "Brian Morden",
    "And the Bungie Auxiliary Players",
};

static const char *const halo_original_credit_names_33[] = {
    "Matt Soell",
};

static const char *const halo_original_credit_names_34[] = {
    "Pete Demoreuille",
    "Tom Gioconda",
    "Joshua Grass",
    "Jason Major",
    "Juan Ramirez",
    "Bob Settles",
};

static const char *const halo_original_credit_names_35[] = {
    "Alexander Seropian",
};

static const char *const halo_original_credit_names_36[] = {
    "Steve Fowler",
};

static const char *const halo_original_credit_names_37[] = {
    "Jon Kimmich",
};

static const char *const halo_original_credit_names_38[] = {
    "Ji Hong",
};

static const char *const halo_original_credit_names_39[] = {
    "Writer: Keith Cirillo",
    "Editor: Tom Brush",
    "Print Artist: Karin Jaques",
};

static const char *const halo_original_credit_names_40[] = {
    "Jule Zuccotti",
    "Ed Fries",
    "Stuart Moulder",
    "Peter Parsons",
    "Chris Cocks",
    "Matt Gradwohl",
    "Michael Sartain",
    "Mark Thomas",
    "Jonathan Sposato",
    "Vic Bonilla",
    "Miguel Chavez",
    "Claude Errera",
    "And all Bungie fans new and old",
};

static const char *const halo_original_credit_names_41[] = {
    "Hamilton - Sandy&Chibi",
    "Marcus - Lynn&kids",
    "M. Soell - All hippos worldwide",
    "Shiek - Ba Ma Guh, Laurel G.",
    "Marty - Marcie",
    "Adrian - stage3,314 Spahr,2DX",
    "Tyson - The r.net and RHL gang",
    "Butcher - Neen Watering Hole",
    "Adam - AprilD ShaneD GregO",
    "Chris L. - minivan+redbriefedBB",
    "Hardy - All my family/friends",
    "Tom - The guys from NoVA",
    "Bernie - lil M+Sha",
    "David C. - Marcy & all the kids",
    "Mat - No more bloody eyes!",
    "Michael - Erika Hall",
    "Paul P. - Laura Drevecky",
    "M. Cody - Betsy & Monkey",
    "Stefan - God, 48th&VanDorn KFC",
    "Joseph - Susan Lusty (&then?)",
    "Carney - ma9",
    "Jay - HDT",
    "Erik - Christine&FatboySlim",
    "M. Wu - Liz and Leia",
    "Paul R. - Keely, Mom & Dad",
    "Chucky - Weedmonkeys",
    "Steve A. - Swetta, Mom & Dad",
    "Luke - Rachel, Mom and Dad",
    "Dave D. - BP,Bean,and Pauls",
    "Lorraine - 4 lettin me join in",
    "John - ConDev",
    "Alex - Laura",
    "Matt - the army",
    "Rick - Sandy,Nathan&Celina",
    "Zach - 1st one, Mom & Dad",
    "Eric A. - Joy",
    "John F. - Kate, M&D, the girls",
    "Chris B. - Jody, Brooklyn",
    "Jaime - Meg, Bugs and the BB's",
    "Ryan - MPlayers, Fans, Guz",
    "R. McLees - Family (new and old)",
    "P. Bertone - Family, Marta & Max",
    "B. Wallace - Milo, Castle Argh",
};

static const char *const halo_original_credit_names_42[] = {
    "Justin Hayward",
};

static const char *const halo_original_credit_names_43[] = {
    "David Dunn",
};

static const char *const halo_original_credit_names_44[] = {
    "Outsiders - thx 4M*!PIA!",
    "Alex - Laura Seropian",
    "Paul B. - Laura Drevecky",
    "Jeffrey - Kate, M&D, the girls",
    "Chris B. - Jody, Maxwell",
};

static const struct halo_original_credit_section halo_original_credit_sections[] = {
    { "Project Lead", halo_original_credit_names_0, 1u },
    { "Lead Producer", halo_original_credit_names_1, 1u },
    { "Producer", halo_original_credit_names_2, 1u },
    { "Programmers", halo_original_credit_names_3, 5u },
    { "Additional Programming", halo_original_credit_names_4, 2u },
    { "Art Director", halo_original_credit_names_5, 1u },
    { "Assistant Art Lead", halo_original_credit_names_6, 1u },
    { "Artists", halo_original_credit_names_7, 11u },
    { "Additional Art", halo_original_credit_names_8, 1u },
    { "Lead Designer", halo_original_credit_names_9, 1u },
    { "Designers", halo_original_credit_names_10, 4u },
    { "Additional Writing", halo_original_credit_names_11, 3u },
    { "Multiplayer Project Lead", halo_original_credit_names_12, 1u },
    { "Multiplayer Programmers", halo_original_credit_names_13, 2u },
    { "Multiplayer Lead Designer", halo_original_credit_names_14, 1u },
    { "Multiplayer Artists", halo_original_credit_names_15, 4u },
    { "Director of Cinematics", halo_original_credit_names_16, 1u },
    { "Cinematic Artists", halo_original_credit_names_17, 5u },
    { "Storyboard Artist", halo_original_credit_names_18, 1u },
    { "Matte and Concept Artist", halo_original_credit_names_19, 1u },
    { "Audio Lead, Sound Design & Original Music", halo_original_credit_names_20, 1u },
    { "Sound Designer", halo_original_credit_names_21, 1u },
    { "Additional Music", halo_original_credit_names_22, 1u },
    { "Additional Sound", halo_original_credit_names_23, 1u },
    { "User Interface Lead", halo_original_credit_names_24, 1u },
    { "User Interface Designer", halo_original_credit_names_25, 1u },
    { "User Interface Programmer", halo_original_credit_names_26, 1u },
    { "Test Manager", halo_original_credit_names_27, 1u },
    { "Test Leads", halo_original_credit_names_28, 2u },
    { "User Testing Lead", halo_original_credit_names_29, 1u },
    { "Testers", halo_original_credit_names_30, 14u },
    { "Voice Talent", halo_original_credit_names_31, 10u },
    { "Additional Voices", halo_original_credit_names_32, 5u },
    { "Damage and Spin", halo_original_credit_names_33, 1u },
    { "Draft Dodgers", halo_original_credit_names_34, 6u },
    { "Executive Producer", halo_original_credit_names_35, 1u },
    { "Product Manager", halo_original_credit_names_36, 1u },
    { "Product Planner", halo_original_credit_names_37, 1u },
    { "Localization Lead", halo_original_credit_names_38, 1u },
    { "Halo Manual", halo_original_credit_names_39, 3u },
    { "Special Thanks", halo_original_credit_names_40, 13u },
    { "Personal Thanks", halo_original_credit_names_41, 43u },
    { "Xbox Manual - Draft Dodgers", halo_original_credit_names_42, 1u },
    { "Xbox Manual - Multiplayer Artists", halo_original_credit_names_43, 1u },
    { "Xbox Manual - Personal Thanks", halo_original_credit_names_44, 5u },
};

static const struct halo_original_credit_page halo_original_credit_pages[] = {
    { "Project Lead:\r\nJason Jones\r\nLead Producer:\r\nHamilton Chu\r\nProducer:\r\nRick Ryan\r\nProgrammers:\r\nChris Butcher" },
    { "Programmers:\r\nBernie Freidin\r\nCharlie Gough\r\nMat Noguchi\r\nMatt Segur\r\nAdditional Programming:\r\nEamon McKenzie\r\nBen Wallace" },
    { "Art Director:\r\nMarcus Lehto\r\nAssistant Art Lead:\r\nSteve Abeyta\r\nArtists:\r\nEric Arroyo\r\nChris Barrett\r\nMark Bernal" },
    { "Artists:\r\nDavid Dunn\r\nChris Hughes\r\nChris Lee\r\nRobert McLees\r\nStephen Okasaki\r\nPaul Russel\r\nShi Kai Wang" },
    { "Artists:\r\nMichael Wu\r\nAdditional Art:\r\nBrian Schultz\r\nLead Designer:\r\nJohn Howard\r\nDesigners:\r\nPaul Bertone" },
    { "Designers:\r\nTyson Green\r\nJaime Griesemer\r\nDan Orzulak\r\nAdditional Writing:\r\nBrannon Boren\r\nMatt Soell\r\nEric Trautmann" },
    { "Multiplayer Project Lead:\r\nMichael Evans\r\nMultiplayer Programmers:\r\nAdrian Perez\r\nStefan Sinclair\r\nMultiplayer Lead Designer:\r\nHardy LeBel" },
    { "Multiplayer Artists:\r\nChris Carney\r\nPeter Marks\r\nDerrick Moore\r\nStephen Okasaki\r\nDirector of Cinematics:\r\nJoseph Staten" },
    { "Cinematic Artists:\r\nSteve Abeyta\r\nPaul Clift\r\nAdam Crockett\r\nLorraine McLees\r\nStephen Okasaki\r\nStoryboard Artist:\r\nLee Wilson" },
    { "Matte and Concept Artist:\r\nCraig Mullins\r\nAudio Lead, Sound Design & Original Music:\r\nMartin O'Donnell\r\nSound Designer:\r\nJay Weinland\r\nAdditional Music:\r\nMichael Salvatori" },
    { "Additional Sound:\r\nAdam Tewes\r\nUser Interface Lead:\r\nMax Hoberman\r\nUser Interface Designer:\r\nDavid Candland\r\nUser Interface Programmer:\r\nStefan Sinclair" },
    { "Test Manager:\r\nHarold Ryan\r\nTest Leads:\r\nCurtis Creamer\r\nRyan Hylland\r\nUser Testing Lead:\r\nKeith Steury" },
    { "Testers:\r\nChris Chamberlain\r\nMike Cody\r\nChuck Cooper\r\nErik Davis\r\nJohn Frey\r\nRick Lockyear\r\nPaul Pedersen" },
    { "Testers:\r\nZach Russell\r\nMatthew Shimabuku\r\nLuke Timmins\r\nJeff Wilson\r\nRoger Wolfson\r\nJeff Kafer\r\nTodd Schultz" },
    { "Voice Talent:\r\nJen Taylor\r\nPete Stacker\r\nTim Dadabo\r\nSteve Downes\r\nTawnya Pettiford-Waites\r\nDavid Scully\r\nMike Madeoy" },
    { "Voice Talent:\r\nMark Dias\r\nChris Wicklund\r\nAndrew McKaige\r\nAdditional Voices:\r\nKen Boynton\r\nTodd Licea\r\nJeff Steitzer" },
    { "Additional Voices:\r\nBrian Morden\r\nAnd the Bungie Auxiliary Players\r\nDamage and Spin:\r\nMatt Soell\r\nDraft Dodgers:\r\nPete Demoreuille\r\nTom Gioconda" },
    { "Draft Dodgers:\r\nJoshua Grass\r\nJason Major\r\nJuan Ramirez\r\nBob Settles\r\nExecutive Producer:\r\nAlexander Seropian" },
    { "Product Manager:\r\nSteve Fowler\r\nProduct Planner:\r\nJon Kimmich\r\nLocalization Lead:\r\nJi Hong\r\nHalo Manual:\r\nWriter: Keith Cirillo" },
    { "Halo Manual:\r\nEditor: Tom Brush\r\nPrint Artist: Karin Jaques\r\nSpecial Thanks:\r\nJule Zuccotti\r\nEd Fries\r\nStuart Moulder\r\nPeter Parsons" },
    { "Special Thanks:\r\nChris Cocks\r\nMatt Gradwohl\r\nMichael Sartain\r\nMark Thomas\r\nJonathan Sposato\r\nVic Bonilla\r\nMiguel Chavez" },
    { "Special Thanks:\r\nClaude Errera\r\nAnd all Bungie fans new and old\r\nPersonal Thanks:\r\nHamilton - Sandy&Chibi\r\nMarcus - Lynn&kids\r\nM. Soell - All hippos worldwide\r\nShiek - Ba Ma Guh, Laurel G." },
    { "Personal Thanks:\r\nMarty - Marcie\r\nAdrian - stage3,314 Spahr,2DX\r\nTyson - The r.net and RHL gang\r\nButcher - Neen Watering Hole\r\nAdam - AprilD ShaneD GregO\r\nChris L. - minivan+redbriefedBB\r\nHardy - All my family/friends" },
    { "Personal Thanks:\r\nTom - The guys from NoVA\r\nBernie - lil M+Sha\r\nDavid C. - Marcy & all the kids\r\nMat - No more bloody eyes!\r\nMichael - Erika Hall\r\nPaul P. - Laura Drevecky\r\nM. Cody - Betsy & Monkey" },
    { "Personal Thanks:\r\nStefan - God, 48th&VanDorn KFC\r\nJoseph - Susan Lusty (&then?)\r\nCarney - ma9\r\nJay - HDT\r\nErik - Christine&FatboySlim\r\nM. Wu - Liz and Leia\r\nPaul R. - Keely, Mom & Dad" },
    { "Personal Thanks:\r\nChucky - Weedmonkeys\r\nSteve A. - Swetta, Mom & Dad\r\nLuke - Rachel, Mom and Dad\r\nDave D. - BP,Bean,and Pauls\r\nLorraine - 4 lettin me join in\r\nJohn - ConDev\r\nAlex - Laura" },
    { "Personal Thanks:\r\nMatt - the army\r\nRick - Sandy,Nathan&Celina\r\nZach - 1st one, Mom & Dad\r\nEric A. - Joy\r\nJohn F. - Kate, M&D, the girls\r\nChris B. - Jody, Brooklyn\r\nJaime - Meg, Bugs and the BB's" },
    { "Personal Thanks:\r\nRyan - MPlayers, Fans, Guz\r\nR. McLees - Family (new and old)\r\nP. Bertone - Family, Marta & Max\r\nB. Wallace - Milo, Castle Argh\r\nXbox Manual - Draft Dodgers:\r\nJustin Hayward" },
    { "Xbox Manual - Multiplayer Artists:\r\nDavid Dunn\r\nXbox Manual - Personal Thanks:\r\nOutsiders - thx 4M*!PIA!\r\nAlex - Laura Seropian\r\nPaul B. - Laura Drevecky\r\nJeffrey - Kate, M&D, the girls\r\nChris B. - Jody, Maxwell" },
};

#endif
