/* Generated by tools/generate_contributor_credits.py; do not edit.
 * Audited source: c6ef70a56795539e374af8b27531896033e46a37
 * Authored non-merge commits; cumulative first-party code lines added.
 * Historical additions include imports and rewrites, not retained LOC.
 */
#ifndef HALO_CONTRIBUTORS_H
#define HALO_CONTRIBUTORS_H

#define HALO_OG_WEBSITE "https://oghalo.com"
#define HALO_OG_CONTRIBUTOR_SOURCE "c6ef70a56795539e374af8b27531896033e46a37"
#define HALO_OG_CONTRIBUTOR_COUNT 19

struct halo_contributor_credit {
    const char *github; /* Verified username, or null for a recorded name. */
    const char *name;
    unsigned commits;
    unsigned added_lines;
    unsigned removed_lines;
};

static const struct halo_contributor_credit halo_contributor_credits[] = {
    { 0, "Jonas Volman", 3272u, 512035u, 80765u },
    { "cybersecurity", "cybersecurity", 93u, 67386u, 79783u },
    { "punpckhdq", "punpckhdq", 90u, 56331u, 2608u },
    { "pfista", "pfista", 80u, 51362u, 6416u },
    { "bnunu", "bnunu", 44u, 4856u, 1778u },
    { "Berthalamew", "Berthalamew", 18u, 23245u, 3092u },
    { "zimm3rmann", "zimm3rmann", 5u, 5189u, 42u },
    { "HaydnTrigg", "HaydnTrigg", 5u, 369u, 17u },
    { "LWSS", "LWSS", 4u, 2938u, 675u },
    { "Englis666", "Englis666", 4u, 145u, 26u },
    { "ficool2", "ficool2", 3u, 1846u, 135u },
    { "bfenty", "bfenty", 2u, 87u, 0u },
    { "thelinkin3000", "thelinkin3000", 2u, 60u, 12u },
    { "ieee802dot11ac", "ieee802dot11ac", 1u, 118u, 54u },
    { "MasonLeeBack", "MasonLeeBack", 1u, 45u, 2u },
    { "MrMilenko", "MrMilenko", 1u, 25u, 10u },
    { "lantos1618", "lantos1618", 1u, 17u, 8u },
    { 0, "Eclisse", 1u, 5u, 0u },
    { "ShaneParslow", "ShaneParslow", 1u, 4u, 1u },
};

#endif
