#!/usr/bin/env python3
"""Generate shared About credits from the audited public Git history snapshot.

The JSON records the source revision, counting method and identity evidence.
Update that audited snapshot before a release, then run this script. --check
verifies that native and in-game credits still match it without changing files.
"""

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "docs/contributors.json"
HEADER = ROOT / "port/linux/include/halo_contributors.h"


def render(snapshot):
    revision = snapshot["source_commit"]
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise ValueError("credits need a full source commit SHA")
    credits = snapshot["contributors"]
    if not credits:
        raise ValueError("credits cannot be empty")
    seen = set()
    for credit in credits:
        name, github = credit["name"], credit["github"]
        if not name or len(name) > 39 or not name.isascii() or "\n" in name:
            raise ValueError("credited names must fit the original game font")
        if github is not None and not re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})", github):
            raise ValueError("invalid verified GitHub username")
        identity = (github or name).casefold()
        if identity in seen:
            raise ValueError("duplicate contributor identity")
        seen.add(identity)
        for key in ("commits", "added_lines", "removed_lines"):
            value = credit[key]
            if type(value) is not int or not 0 <= value <= 0xFFFFFFFF:
                raise ValueError("credits totals must fit an unsigned 32-bit integer")
        if not credit["commits"] or not credit["added_lines"]:
            raise ValueError("contributors must have authored code-changing commits")
    credits = sorted(credits, key=lambda c: (-c["commits"], -c["added_lines"], c["name"].casefold()))
    lines = [
        "/* Generated by tools/generate_contributor_credits.py; do not edit.",
        " * Audited source: " + revision,
        " * Authored non-merge commits; cumulative first-party code lines added.",
        " * Historical additions include imports and rewrites, not retained LOC.",
        " */",
        "#ifndef HALO_CONTRIBUTORS_H",
        "#define HALO_CONTRIBUTORS_H",
        "",
        '#define HALO_OG_WEBSITE "https://oghalo.com"',
        '#define HALO_OG_CONTRIBUTOR_SOURCE "' + revision + '"',
        "#define HALO_OG_CONTRIBUTOR_COUNT " + str(len(credits)),
        "",
        "struct halo_contributor_credit {",
        "    const char *github; /* Verified username, or null for a recorded name. */",
        "    const char *name;",
        "    unsigned commits;",
        "    unsigned added_lines;",
        "    unsigned removed_lines;",
        "};",
        "",
        "static const struct halo_contributor_credit halo_contributor_credits[] = {",
    ]
    for credit in credits:
        github = json.dumps(credit["github"]) if credit["github"] else "0"
        lines.append("    { %s, %s, %uu, %uu, %uu }," % (
            github, json.dumps(credit["name"]), credit["commits"],
            credit["added_lines"], credit["removed_lines"]))
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(json.loads(SNAPSHOT.read_text()))
    if args.check:
        if not HEADER.exists() or HEADER.read_text() != expected:
            parser.exit(1, "About credits are stale; run tools/generate_contributor_credits.py\n")
        print("About credits match the audited contributor snapshot")
    else:
        HEADER.write_text(expected)
        print("Generated " + str(HEADER.relative_to(ROOT)))


if __name__ == "__main__":
    main()
