#!/usr/bin/env python3
"""Generate shared original Xbox credits and readable in-game About pages.

The source roster and provenance live in docs/original-xbox-credits.json.
Keep roles in their original order; repeat a role when it spans pages and
never leave a heading without a credited name below it.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROSTER = ROOT / "docs/original-xbox-credits.json"
HEADER = ROOT / "port/linux/include/halo_original_credits.h"
LINES_PER_PAGE = 8


def credit_pages(sections):
    pages, lines = [], []
    for section in sections:
        if LINES_PER_PAGE - len(lines) < 2:
            pages.append("\r\n".join(lines))
            lines = []
        lines.append(section["role"] + ":")
        for name in section["names"]:
            if len(lines) == LINES_PER_PAGE:
                pages.append("\r\n".join(lines))
                lines = [section["role"] + ":"]
            lines.append(name)
    if lines:
        pages.append("\r\n".join(lines))
    return pages


def validate_text(value, label):
    if not isinstance(value, str) or not value or not value.isascii() or any(
        ord(character) < 32 or ord(character) > 126 for character in value
    ):
        raise ValueError(label + " must be nonempty printable ASCII for the original game font")


def render(roster):
    validate_text(roster["title"], "title")
    sections = roster["sections"]
    if not sections:
        raise ValueError("original credits cannot be empty")
    for section in sections:
        validate_text(section["role"], "role")
        if not section["names"]:
            raise ValueError("every role needs credited names")
        seen = set()
        for name in section["names"]:
            validate_text(name, "name")
            if name in seen:
                raise ValueError("duplicate name within a role: " + name)
            seen.add(name)
    sources = roster["sources"]
    if not sources or not all(source["url"].startswith("https://") for source in sources):
        raise ValueError("credits need HTTPS source links")
    pages = credit_pages(sections)
    lines = [
        "/* Generated by tools/generate_original_credits.py; do not edit.",
        " * Original Xbox (2001) roster: docs/original-xbox-credits.json.",
        " * Role order and source differences are recorded with the roster.",
        " */",
        "#ifndef HALO_ORIGINAL_CREDITS_H",
        "#define HALO_ORIGINAL_CREDITS_H",
        "",
        "#define HALO_OG_ORIGINAL_CREDITS_TITLE " + json.dumps(roster["title"]),
        "#define HALO_OG_ORIGINAL_CREDITS_SOURCE_URL " + json.dumps(sources[0]["url"]),
        "#define HALO_OG_ORIGINAL_CREDIT_SECTION_COUNT " + str(len(sections)),
        "#define HALO_OG_ORIGINAL_CREDIT_PAGE_COUNT " + str(len(pages)),
        "",
        "struct halo_original_credit_section {",
        "    const char *role;",
        "    const char *const *names;",
        "    unsigned count;",
        "};",
        "struct halo_original_credit_page {",
        "    const char *text;",
        "};",
        "",
    ]
    for index, section in enumerate(sections):
        lines.append("static const char *const halo_original_credit_names_%u[] = {" % index)
        lines.extend("    " + json.dumps(name) + "," for name in section["names"])
        lines.extend(["};", ""])
    lines.append("static const struct halo_original_credit_section halo_original_credit_sections[] = {")
    for index, section in enumerate(sections):
        lines.append("    { %s, halo_original_credit_names_%u, %uu }," % (
            json.dumps(section["role"]), index, len(section["names"])))
    lines.extend(["};", "", "static const struct halo_original_credit_page halo_original_credit_pages[] = {"])
    lines.extend("    { " + json.dumps(page) + " }," for page in pages)
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(json.loads(ROSTER.read_text()))
    if args.check:
        if not HEADER.exists() or HEADER.read_text() != expected:
            parser.exit(1, "Original About credits are stale; run tools/generate_original_credits.py\n")
        print("Original About credits match the sourced Xbox roster")
    else:
        HEADER.write_text(expected)
        print("Generated " + str(HEADER.relative_to(ROOT)))


if __name__ == "__main__":
    main()
